################################################################################
# Automatically-generated file. Do not edit!
################################################################################

SHELL = cmd.exe

# Each subdirectory must supply rules for building sources it contributes
%.obj: ../%.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccs1250/ccs/tools/compiler/ti-cgt-c2000_22.6.1.LTS/bin/cl2000" -v28 -ml -mt --cla_support=cla2 --float_support=fpu64 --idiv_support=idiv0 --tmu_support=tmu0 --vcu_support=vcrc -Ooff --include_path="D:/CCS/Workspace Ghep Noi/AC BAT CODE V2 CPU1/include" --include_path="D:/CCS/Workspace Ghep Noi/AC BAT CODE V2 CPU1/library/Math/CLAmath/include" --include_path="D:/CCS/Workspace Ghep Noi/AC BAT CODE V2 CPU1/library/Math/IQmath/include" --include_path="D:/CCS/Workspace Ghep Noi/AC BAT CODE V2 CPU1/library/App_lib/Controller/include" --include_path="D:/CCS/Workspace Ghep Noi/AC BAT CODE V2 CPU1/library/App_lib/Motor/include" --include_path="D:/CCS/Workspace Ghep Noi/AC BAT CODE V2 CPU1/library/App_lib/MPPT/include" --include_path="D:/CCS/Workspace Ghep Noi/AC BAT CODE V2 CPU1/library/App_lib/Observer/include" --include_path="D:/CCS/Workspace Ghep Noi/AC BAT CODE V2 CPU1/library/App_lib/Other/include" --include_path="D:/CCS/Workspace Ghep Noi/AC BAT CODE V2 CPU1/library/App_lib/Phaselockedloop/include" --include_path="D:/CCS/Workspace Ghep Noi/AC BAT CODE V2 CPU1/library/App_lib/PWM/include" --include_path="D:/CCS/Workspace Ghep Noi/AC BAT CODE V2 CPU1/library/App_lib/Transform/include" --include_path="D:/CCS/Workspace Ghep Noi/AC BAT CODE V2 CPU1" --include_path="C:/ti/c2000/C2000Ware_5_03_00_00/device_support/f2838x/common/include" --include_path="C:/ti/c2000/C2000Ware_5_03_00_00/device_support/f2838x/headers/include" --include_path="C:/ti/ccs1250/ccs/tools/compiler/ti-cgt-c2000_22.6.1.LTS/include" --advice:performance=all --define=USE_20MHZ_XTAL --define=DEBUG --define=CPU1 --diag_suppress=10063 --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --abi=eabi --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

%.obj: ../%.cla $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccs1250/ccs/tools/compiler/ti-cgt-c2000_22.6.1.LTS/bin/cl2000" -v28 -ml -mt --cla_support=cla2 --float_support=fpu64 --idiv_support=idiv0 --tmu_support=tmu0 --vcu_support=vcrc -Ooff --include_path="D:/CCS/Workspace Ghep Noi/AC BAT CODE V2 CPU1/include" --include_path="D:/CCS/Workspace Ghep Noi/AC BAT CODE V2 CPU1/library/Math/CLAmath/include" --include_path="D:/CCS/Workspace Ghep Noi/AC BAT CODE V2 CPU1/library/Math/IQmath/include" --include_path="D:/CCS/Workspace Ghep Noi/AC BAT CODE V2 CPU1/library/App_lib/Controller/include" --include_path="D:/CCS/Workspace Ghep Noi/AC BAT CODE V2 CPU1/library/App_lib/Motor/include" --include_path="D:/CCS/Workspace Ghep Noi/AC BAT CODE V2 CPU1/library/App_lib/MPPT/include" --include_path="D:/CCS/Workspace Ghep Noi/AC BAT CODE V2 CPU1/library/App_lib/Observer/include" --include_path="D:/CCS/Workspace Ghep Noi/AC BAT CODE V2 CPU1/library/App_lib/Other/include" --include_path="D:/CCS/Workspace Ghep Noi/AC BAT CODE V2 CPU1/library/App_lib/Phaselockedloop/include" --include_path="D:/CCS/Workspace Ghep Noi/AC BAT CODE V2 CPU1/library/App_lib/PWM/include" --include_path="D:/CCS/Workspace Ghep Noi/AC BAT CODE V2 CPU1/library/App_lib/Transform/include" --include_path="D:/CCS/Workspace Ghep Noi/AC BAT CODE V2 CPU1" --include_path="C:/ti/c2000/C2000Ware_5_03_00_00/device_support/f2838x/common/include" --include_path="C:/ti/c2000/C2000Ware_5_03_00_00/device_support/f2838x/headers/include" --include_path="C:/ti/ccs1250/ccs/tools/compiler/ti-cgt-c2000_22.6.1.LTS/include" --advice:performance=all --define=USE_20MHZ_XTAL --define=DEBUG --define=CPU1 --diag_suppress=10063 --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --abi=eabi --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

%.obj: ../%.asm $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccs1250/ccs/tools/compiler/ti-cgt-c2000_22.6.1.LTS/bin/cl2000" -v28 -ml -mt --cla_support=cla2 --float_support=fpu64 --idiv_support=idiv0 --tmu_support=tmu0 --vcu_support=vcrc -Ooff --include_path="D:/CCS/Workspace Ghep Noi/AC BAT CODE V2 CPU1/include" --include_path="D:/CCS/Workspace Ghep Noi/AC BAT CODE V2 CPU1/library/Math/CLAmath/include" --include_path="D:/CCS/Workspace Ghep Noi/AC BAT CODE V2 CPU1/library/Math/IQmath/include" --include_path="D:/CCS/Workspace Ghep Noi/AC BAT CODE V2 CPU1/library/App_lib/Controller/include" --include_path="D:/CCS/Workspace Ghep Noi/AC BAT CODE V2 CPU1/library/App_lib/Motor/include" --include_path="D:/CCS/Workspace Ghep Noi/AC BAT CODE V2 CPU1/library/App_lib/MPPT/include" --include_path="D:/CCS/Workspace Ghep Noi/AC BAT CODE V2 CPU1/library/App_lib/Observer/include" --include_path="D:/CCS/Workspace Ghep Noi/AC BAT CODE V2 CPU1/library/App_lib/Other/include" --include_path="D:/CCS/Workspace Ghep Noi/AC BAT CODE V2 CPU1/library/App_lib/Phaselockedloop/include" --include_path="D:/CCS/Workspace Ghep Noi/AC BAT CODE V2 CPU1/library/App_lib/PWM/include" --include_path="D:/CCS/Workspace Ghep Noi/AC BAT CODE V2 CPU1/library/App_lib/Transform/include" --include_path="D:/CCS/Workspace Ghep Noi/AC BAT CODE V2 CPU1" --include_path="C:/ti/c2000/C2000Ware_5_03_00_00/device_support/f2838x/common/include" --include_path="C:/ti/c2000/C2000Ware_5_03_00_00/device_support/f2838x/headers/include" --include_path="C:/ti/ccs1250/ccs/tools/compiler/ti-cgt-c2000_22.6.1.LTS/include" --advice:performance=all --define=USE_20MHZ_XTAL --define=DEBUG --define=CPU1 --diag_suppress=10063 --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --abi=eabi --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '


